[app]
title = '秣锐软件'

[manifest]
name = '秣锐软件'
short_name = '秣锐软件'
start_url = '.'
display = 'standalone'
background_color = '#fff'
description = '秣锐软件'
[[manifest.icons]]
src = '/image/coffee_bean.png'
sizes = '128x128'
type = 'image/png'