[[response]]
keyword=6
text= {
	type= 'book'
	book= 'Photoshop CS5图层、通道、蒙版与抠图技术精粹',
	content= '百度网盘链接：https://pan.baidu.com/s/1Trby3buePiHoh5OXqMuTvw 
提取码：fen5'
}

[[response]]
keyword=7
text= {
	type= 'book'
	book= '《Adobe Photoshop CS6标准培训教材[精品]》ACAA专家委员会',
	content= '百度网盘链接：https://pan.baidu.com/s/1xpYVzGwwkyJsaoBE0rlZeQ 
提取码：sb78'
}